# Project: MineSweeper
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = MineSweeper_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"D:/Dev-Cpp/lib"  
INCS =  -I"D:/Dev-Cpp/include" 
CXXINCS =  -I"D:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/Dev-Cpp/include/c++/3.4.2"  -I"D:/Dev-Cpp/include" 
BIN  = MineSweeper.exe
CXXFLAGS = $(CXXINCS)   -lwinmm
CFLAGS = $(INCS)   -lwinmm
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before MineSweeper.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "MineSweeper.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

MineSweeper_private.res: MineSweeper_private.rc icon.rc 
	$(WINDRES) -i MineSweeper_private.rc --input-format=rc -o MineSweeper_private.res -O coff 
